-- NOTE: This file is auto generated by ./sql-generator

-- ClassificationRepository.getCategories
select
  *
from
  "classification_category"
order by
  "name" asc

-- ClassificationRepository.getCategoriesWithPrompts
select
  "c"."id",
  "c"."name",
  "c"."similarity",
  "c"."action",
  "c"."enabled",
  "c"."createdAt",
  "c"."updatedAt",
  "p"."prompt"
from
  "classification_category" as "c"
  left join "classification_prompt_embedding" as "p" on "p"."categoryId" = "c"."id"
order by
  "c"."name" asc

-- ClassificationRepository.getCategory
select
  *
from
  "classification_category"
where
  "id" = $1

-- ClassificationRepository.getPromptEmbeddings
select
  *
from
  "classification_prompt_embedding"
where
  "categoryId" = $1

-- ClassificationRepository.getEnabledCategoriesWithEmbeddings
select
  "c"."id" as "categoryId",
  "c"."name",
  "c"."similarity",
  "c"."action",
  "p"."id" as "promptId",
  "p"."prompt",
  "p"."embedding"
from
  "classification_category" as "c"
  inner join "classification_prompt_embedding" as "p" on "p"."categoryId" = "c"."id"
where
  "c"."enabled" = $1
